<!DOCTYPE html>
<html>
	<head>
		<title><?php echo $title; ?></title>
		<meta charset="UTF-8"/>
		<link rel="icon" href="favicon.ico"/>
		<link rel="stylesheet" type="text/css" href="/css/style.css"/>
		<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin"/>
		<script src="js/displayOptions.js"></script>
		<script src="https://use.fontawesome.com/646b36f2aa.js"></script>
	</head>
	<body>

		<div id="wrapper" align="center">
