<!DOCTYPE html>
<html>
	<head>
		<title><?php echo $title; ?></title>
		<meta charset="UTF-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="Cloud file storage with user-managed encryption.">
		<meta name="keywords" content="Aaron Horler, Samuel Thwin, Vanja Novakovic, Phu Dang, Building IT Systems, RMIT">
		<meta name="url" content="https://aleator.stream/">
		<meta name="referrer" content="no-referrer">
		<meta http-equiv="x-dns-prefetch-control" content="off">
		<meta name="format-detection" content="telephone=no">
		<link rel="icon" href="/favicon.ico"/>
		<link rel="stylesheet" type="text/css" href="/css/style.css"/>
		<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin"/>
		<link rel="author" href="humans.txt">
		<script src="/js/displayOptions.js"></script>
		<script src="https://use.fontawesome.com/646b36f2aa.js"></script>
	</head>
	<body>

		<div id="wrapper" align="center">
